apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: flask-app
  name: vault-static-secret-flask-app-secret
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: flask-app/flask-app-secret
  refreshAfter: 10s
  destination:
    create: true
    name: flask-app-secret
  rolloutRestartTargets:
  - kind: Deployment
    name: flask-app
